
OrdererOrgs:
  - Name: Orderer
    Domain: trucker.com
    Specs:
      - Hostname: orderer
PeerOrgs:
  - Name: Org1
    Domain: org1.trucker.com
    Template:
      Count: 1
    Users:
      Count: 1

  - Name: Org2
    Domain: org2.trucker.com
    Template:
      Count: 1
    Users:
      Count: 5

  - Name: Org3
    Domain: org3.trucker.com
    Template:
      Count: 1
    Users:
      Count: 5